arch: amd64
os: linux
dist: focal

services:
- docker

archlinux:
  repos:
  - archlinuxfr=http://repo.archlinux.fr/$arch
  packages:
  - p7zip
  - wine
  - wine-mono
  - wine-gecko
  - xorg-xwininfo
  - wqy-microhei
  - lib32-alsa-lib
  - lib32-alsa-plugins
  - lib32-libpulse
  - lib32-openal
  - lib32-mpg123
  - lib32-gnutls
  script:
  - "makepkg"
  - "./gen.sh -m"

script:
- "curl -s https://raw.githubusercontent.com/countstarlight/arch-travis/master/arch-travis.sh | bash"

deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  token: $GH_TOKEN
  file_glob: true
  file:
    - "deepin-wine-qq*.pkg*"
  on:
    tags: true
    all_branches: true
    repo: countstarlight/deepin-wine-qq-arch
