#!/usr/bin/env python3

# -*- coding:utf-8 -*-
import json
from sys import argv
from requests import get

def main(home_path):
    try:
        group_list = get('http://127.0.0.1:9090/proxies').json()['proxies']
        selector_dic = dict()
        for curr_group in group_list:
            if group_list[curr_group]['type'] == 'Selector':
                selector_dic[curr_group] = group_list[curr_group]['now']
        conf_path = "%s/.config/last_select" % (home_path)
        conf_file = open(conf_path, 'w', encoding='utf-8')
        print('selection of proxy is saved into %s' % (conf_path))
        json.dump(selector_dic, conf_file)
    except (ConnectionError, FileExistsError, FileNotFoundError):
        return True
    except (ConnectionError):
        print('ConnectionError')
        return False


if (__name__ == '__main__'):
    try:
        ret = main(argv[1])
    except IndexError:
        print('IndexError: No home path founded')
